services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-personal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: dracu
      MYSQL_PASSWORD: dracu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_personal:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data_personal:
